-- MEMBER테이블 생성문(회원가입, 로그인 시 필요)
CREATE TABLE MEMBER (
    NO NUMBER PRIMARY KEY,
    ID VARCHAR2(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(10) DEFAULT 'ROLE_USER',
    NAME VARCHAR2(15) NOT NULL,
    BIRTH VARCHAR2(15),
    NICKNAME VARCHAR2(50),
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(13),
    ADDRESS VARCHAR2(100),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN MEMBER.NO IS '회원번호';
COMMENT ON COLUMN MEMBER.ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.PASSWORD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.ROLE IS '회원타입';
COMMENT ON COLUMN MEMBER.NAME IS '회원명';
COMMENT ON COLUMN MEMBER.BIRTH IS '회원생일';
COMMENT ON COLUMN MEMBER.NICKNAME IS '회원별명';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '정보수정일';

CREATE SEQUENCE SEQ_UNO;

INSERT INTO MEMBER (
    NO, 
    ID, 
    PASSWORD, 
    ROLE,
    NAME,
    BIRTH,
    NICKNAME, 
    EMAIL,
    PHONE,
    ADDRESS,
    STATUS, 
    ENROLL_DATE, 
    MODIFY_DATE
) VALUES(
    SEQ_UNO.NEXTVAL, 
    'admin2', 
    '1234', 
    'ROLE_ADMIN', 
    '관리자',
    '1800-01-01',
    '바비',
    'admin@iei.or.kr',
    '010-7777-1111',
    '서울시 서초구',
    DEFAULT,
    DEFAULT,
    DEFAULT
);

COMMIT;

-- 테이블 삭제문
--DROP TABLE MEMBER;
--DROP SEQUENCE SEQ_UNO;

-- SALEBOARD 생성문(판매게시판)
CREATE TABLE SALEBOARD (
    SALE_NO NUMBER PRIMARY KEY,
    SALE_WRITER_NO NUMBER NOT NULL,
    SALE_TITLE VARCHAR2(100) NOT NULL,
    SALE_PRICE VARCHAR2(50) NOT NULL,
    SALE_CATEGORY VARCHAR2(50) NOT NULL,
    SALE_CONTENT VARCHAR2(1000) NOT NULL,
    SALE_FILENAME VARCHAR2(100),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    WISH_STATUS VARCHAR2(1) DEFAULT 'N' CHECK (WISH_STATUS IN('Y', 'N')),
    GOODS_STATUS VARCHAR2(10) DEFAULT 'USED' CHECK (GOODS_STATUS IN('USD', 'NOP', 'NEW')),
    DEAL_STATUS VARCHAR2(10) DEFAULT 'DRCT' CHECK (DEAL_STATUS IN('DRCT', 'MAIL', 'SAFE')),
    SALE_DATE DATE DEFAULT SYSDATE 
);

COMMENT ON COLUMN SALEBOARD.SALE_NO IS '판매글 번호';
COMMENT ON COLUMN SALEBOARD.SALE_WRITER_NO IS '판매글 작성자';
COMMENT ON COLUMN SALEBOARD.SALE_TITLE IS '판매글 제목';
COMMENT ON COLUMN SALEBOARD.SALE_PRICE IS '판매 가격';
COMMENT ON COLUMN SALEBOARD.SALE_CATEGORY IS '카테고리';
COMMENT ON COLUMN SALEBOARD.SALE_CONTENT IS '상품 내용';
COMMENT ON COLUMN SALEBOARD.SALE_FILENAME IS '판매상품자료';
COMMENT ON COLUMN SALEBOARD.STATUS IS '판매 상태값(Y/N)';
COMMENT ON COLUMN SALEBOARD.WISH_STATUS IS '찜한 상태값(Y/N)';
COMMENT ON COLUMN SALEBOARD.GOODS_STATUS IS '물건 상태값(USD/NOP/NEW)';
COMMENT ON COLUMN SALEBOARD.DEAL_STATUS IS '거래 방식(DRCT/MAIL/SAFE)';
COMMENT ON COLUMN SALEBOARD.SALE_DATE IS '판매글 작성일';

CREATE SEQUENCE SEQ_SALEBOARD_NO;



-- 공지테이블 작성 쿼리문 
CREATE TABLE NOTICE (	
    NOTICE_NO NUMBER,
    WRITER_NO NUMBER, 
	NOTICE_TITLE VARCHAR2(100), 
	NOTICE_CONTENT VARCHAR2(4000), 
	READCOUNT NUMBER DEFAULT 0, 
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    CREATE_DATE DATE DEFAULT SYSDATE, 
    MODIFY_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_NOTICE_NO PRIMARY KEY(NOTICE_NO),
    CONSTRAINT FK_NOTICE_WRITER FOREIGN KEY(WRITER_NO) REFERENCES MEMBER(NO) ON DELETE SET NULL
);

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지번호';
COMMENT ON COLUMN NOTICE.WRITER_NO IS '작성자';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지내용';
COMMENT ON COLUMN NOTICE.READCOUNT IS '조회수';
COMMENT ON COLUMN NOTICE.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN NOTICE.CREATE_DATE IS '공지등록일';
COMMENT ON COLUMN NOTICE.MODIFY_DATE IS '공지수정일';

CREATE SEQUENCE SEQ_NOTICE_NO;
-- 시퀀스 삭제 명령어↓
--DROP SEQUENCE 시퀀스명;

SELECT SEQ_NOTICE_NO.CURRVAL FROM DUAL;


-- 테이블 삭제 명령어↓
DROP TABLE NOTICE;
DROP SEQUENCE SEQ_NOTICE_NO;


INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '유캠프 운영정책 안내',  '운영정책에 대해서 말씀드립니다.', DEFAULT, 'Y', SYSDATE, SYSDATE);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '안전거래 캠페인에 따른 공지',  '안전거래 캠페인에 대해서 말씀드립니다.', DEFAULT, 'Y', SYSDATE, SYSDATE);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '게시판 거래 정책 안내',  '게시판 거래 정책에 대해서 말씀드립니다.', DEFAULT, 'Y', SYSDATE, SYSDATE);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '개인정보처리방침',  '개인정보 처리방침에 대해서 말씀드립니다.', DEFAULT, 'Y', SYSDATE, SYSDATE);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '지역광고 후기 이벤트 당첨자를 공개해요!',  '지역광고 후기 이벤트 당첨자를 공개합니다. 당첨자는...감자킹님입니다!', DEFAULT, 'Y', SYSDATE, SYSDATE);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '[이벤트] 반려동물과 함께 캠핑을 즐기자!',  '반려동물과 함께 캠핑을 즐기자! 이벤트 안내입니다.', DEFAULT, 'Y', SYSDATE, SYSDATE);

COMMIT;

SELECT COUNT(*) FROM NOTICE WHERE STATUS='Y';


SELECT RNUM, NOTICE_NO, NOTICE_TITLE, ID, CREATE_DATE, READCOUNT, STATUS FROM 
(SELECT ROWNUM AS RNUM, 
NOTICE_NO, 
NOTICE_TITLE, ID, 
CREATE_DATE, READCOUNT, 
STATUS FROM 
(SELECT N.NOTICE_NO, 
N.NOTICE_TITLE, 
M.ID, 
N.CREATE_DATE, 
N.READCOUNT, 
N.STATUS 
FROM NOTICE N JOIN MEMBER M ON(N.WRITER_NO = M.NO) 
WHERE N.STATUS = 'Y' ORDER BY 
N.NOTICE_NO DESC)) 
WHERE RNUM BETWEEN 1 and 1;
